project:
  type: website
  output-dir: docs
  
  resources:
  - Review of McKinsey.pdf
  - Assignment 3.pdf
  - Review of Hadley Wickham.pdf
  - Notes-pitfall.pdf
  - Assignment 2.pdf
  - Assignment_1.pdf
  - Review of JAD.pdf
  - Review of Edward Tufte.pdf
  - Tzu-Yuanâ€™s Data Guide Checklist.pdf
  - Tzu-Yuan,Chen_review.pdf

website:
  title: "Tzu-Yuan Chen"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd 
      - text: Data Visualization
        menu:
          - text: Assignments
            href: EPPS6356.qmd#assignments
          - text: Final Project
            href: EPPS6356.qmd#final-project
          - text: Reviews
            href: EPPS6356.qmd#reviews
          - text: Notes
            href: EPPS6356.qmd#notes
          - text: Checklist
            href: EPPS6356.qmd#checklist
      - text: Information Management
        menu:
          - text: Assignments
            href: EPPS6354.qmd
          - text: Final Project
            href: EPPS6354.qmd#final-project
      - text: Machine Learning
        menu:
          - text: Assignments
            href: ML.qmd#assignments
      - text: Deep Learning
        menu:
          - text: Assignments
            href: DL.qmd#assignments

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    page-layout: article
    css: styles.css
