project:
  type: website
  output-dir: docs
  
  resources:
  - Review of McKinsey.pdf
  - Assignment 3.pdf
  - Review of Hadley Wickham.pdf
  - Notes-pitfall.pdf
  - Assignment 2.pdf
  - Assignment_1.pdf
  - Review of JAD.pdf
  - Review of Edward Tufte.pdf
  - Tzu-Yuanâ€™s Data Guide Checklist.pdf
  - Tzu-Yuan,Chen_review.pdf
  - SVD_app.py

website:
  title: "Tzu-Yuan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: BS of AM
        menu:
          - text: Overview
            href: AM.qmd
          - text: Quantum Bayesian Inference
            href: AM_thesis.qmd
      - text: MS of DSIC
        menu:
          - text: Overview
            href: DSIC.qmd
          - text: ML & Data Science
            href: ML.qmd#assignments
          - text: Deep Learning
            href: DL.qmd#assignments
          - text: Big Data Analysis
            href: BigData.qmd#assignments
          - text: Data Analysis Math
            href: DataAnalysis.qmd#assignments
      - text: MS of SDAR
        menu:
          - text: Overview
            href: SDAR.qmd
          - text: GIS & Python
            href: GISPY.qmd#assignments
          - text: Data Visualization
            href: EPPS6356.qmd#assignments
          - text: Information Management
            href: EPPS6354.qmd
      - text: CV
        href: CV.qmd

jupyter: python3

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    page-layout: article
    css: styles.scss
